# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d231eb33abc41ed2bd38a3903d5cb119ad5150aacdc8a97c1e559fe7321a973320f798e9b47e1c820fc4e932576bc417025b8e4fe494c3507df04a38147bf6e4

test:
  secret_key_base: 8da9f43bdc77d5156606275e400d77662a133039c3c71b5e8a758a99a702063074290838d4e6cf9cbb09824b26b81cedd0e56f59997258f3536614b33eca732d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
